language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose
# Run scripts
script:
  - docker-compose run app sh -c "python manage.py test && flake8"
deploye:
  provider: heroku
  api_key: EwtwuB6u7HSYUQfQwbtU2kjksCTuugeK10hEh+axm7nrT931GyzTPQID6lqTcuLpst+4Ll6lurYvfqdMuqFXRDec5lrT0fLOjp67wlsVuQhsKmVqQa0MKvvINFyGtSdZbudKBqlKkJqeBzPAkGFUEDyQbYPVZKdXkFhcm2vLuTjpM7R6ZXC8lRHIxdcv6i7qfx0N25mD78q0ZZHirHkgXyMoLKfhxswYztco6/ynkEtXg9TcR6oMPE+xFl+VTodBoUzm8umkcK8VmrbYDNoEfd+oTX8Gm5M7451Et7XCG+mgNrw778Q5FGL3aYdTzm2OiL9yKFKrZiuSKUmIbnybO2AF1Hzm4gQI5TvJBDFgEtIavJ45wEvsCH6AmRqwXfexo7vl1tn6UhU/JuyUgHGwFZfmGJH9lDWZhNZ9SGwUH/yMYOBsnEqpCSx45xWcF/NDETy8SG7TUXrDb+4bo6lbuBP4L9Vnbz1TFseym3Gnuq0L+RkQ0NdX1bYE1FoacC2bqtFAnlNCmgd/xqcsuTLsrcJm7Rv6HSvVCF/XypKBmWxBGlVZcYqu5eaI58S5g5DrxAnGDsOwrejV58bUkeV4LSSD6xUxTWGX4Uht6TsoptWZhcOuqYhV+yr5kHn3T9Y5UwFZenGhoDFMx0NsrJBTwMM3S3hWdC93faw8KSCulTo=
  app: python-restapis
  on:
    repo: everythingisdata/python-restapis
